Feature/auth middleware
DuolearnHQ/Tasky pull request #13
Opened 2024-02-24 16:15 UTC by Sandeep1908

**Description**
This pull request enhances the authentication middleware by adding comprehensive documentation using JSDoc comments. Documentation is an essential aspect of maintaining and understanding codebases, especially for shared modules like middleware, as it facilitates easier usage and maintenance for other developers.

2024-02-28 08:11 UTC, pavankpdev requested changes

2024-02-28 08:11 UTC, pavankpdev commented on middlewares/auth.js
> +  // TODO: implement the auth middleware here
remove the TODO comment

2024-02-28 08:11 UTC, pavankpdev commented on middlewares/auth.js
> +    req.user = user;
adding user objects directly from the DB exposes a lot of sensitive data that is not required, such as passwords and others. Let's assign the user id to `req.user`

2024-02-28 08:11 UTC, pavankpdev commented on middlewares/auth.js
> +    throw new ApiError(401, error?.message || "Invalid access token");
here the status code should be 400

2024-02-28 08:11 UTC, pavankpdev commented on services/user/index.js
> +  const user=await userModel.findById({
you can pass the id directly, `findById(id)` no need to complicate it

2024-03-15 18:46 UTC, pavankpdev requested changes
Hey @Sandeep1908 good job on the PR, just one more minor change required

2024-03-15 18:46 UTC, pavankpdev commented on services/user/index.js
>    const user=await userModel.findById({
You can pass the id directly `findById(id)`, here refer this [doc](https://mongoosejs.com/docs/api/model.html#Model.findById())

2024-03-20 06:35 UTC, pavankpdev commented on services/user/index.js
Great

2024-03-20 06:35 UTC, pavankpdev reviewed
Looks good @Sandeep1908 I'll test this change and then I'll merge it

2024-03-28 04:31 UTC, pavankpdev commented
Hey @Sandeep1908 after testing the middleware I notices one major issue. 
The `APIError` reusable module we have, crashes the entire server instead of gracefully throwing error and sending it to the client. 

We can do this. 
1. We dispatch error response with status and message using `res` 
2. Or we set a global listener that checks for the error and responds the client with the error. 

You can choose any one of these.

2024-04-08 06:37 UTC, Sandeep1908 commented
@pavankpdev , please check I have used res for error handling

2024-06-04 09:32 UTC, pavankpdev commented on controllers/auth/index.js
> +    return res.status(500).json({message: "ERRR in login"});
typo 😬

2024-06-04 09:33 UTC, pavankpdev approved these changes
@Sandeep1908 merging the PR, thanks for the contribution and your patience.

2024-06-04 09:33 UTC, merged